sudo: required
language: generic
services:
  - docker

before_install:
  - sudo apt-get install sshpass
  - sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no root@68.183.230.245 

script:

deploy:
  provider: script
  script: bash ./travis_deploy.sh
  on:
    branch: master